name 'Analytical Labs-os'
version '1.0'

author 'Tom Barber'
license ''
project_page ''
source ''
summary ''
description ''
dependency 'Analytical Labs/common', '==1.0'
dependency 'Analytical Labs/apt', '==1.0'
dependency 'Analytical Labs/locales', '==1.0'
